name: three_r2c_automation

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pyyaml
  - pytest

  # Conda scientific stack
  - numpy
  - pandas
  - scikit-learn
  - matplotlib

  # Pip-only packages
  - pip:
      - filterpy
      - eppy

      