project:
  name: building_rom_automation

paths:
  raw_idf_root: data/raw/resstock_idfs
  output_root: data/intermediate/perturbed_idfs

selection:
  mode: batch         # single | batch
  single_file: null   # used when mode=single
  pattern: "*.idf"    # used when mode=batch
  recursive: true

output:
  overwrite: false
  suffix: "__edited"

edits:
  simulation_control:
    run_period:
      begin_month: 1
      begin_day_of_month: 1
      end_month: 1
      end_day_of_month: 31

    timestep_per_hour: 4

  setpoints:
    heating:
      enabled: true
      schedule_type: day_interval
      schedule_name: heating setpoint day
      default_value_c: 20.0
      intervals:
        - until: "06:00"
          value_c: 18.0
        - until: "22:00"
          value_c: 21.0
        - until: "24:00"
          value_c: 18.0

    cooling:
      enabled: true
      schedule_type: day_interval
      schedule_name: cooling setpoint day
      default_value_c: 24.0
      intervals:
        - until: "06:00"
          value_c: 26.0
        - until: "22:00"
          value_c: 24.0
        - until: "24:00"
          value_c: 26.0


  perturbation:
    enabled: false
    cooling_offset_c: 0.0
    heating_offset_c: 0.0